<a href="https://colab.research.google.com/github/demigod1208/demigod1208/blob/main/Day_6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Array Creation

# By Zeros And Ones

import numpy as np

zero = np.zeros((3,4))
print(zero)
print()
one = np.ones((3,4))
print(one)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [8]:
#By existing data

#Array()function

import  numpy as np

a = np.array([1,2,3,4,5])
print(a)
print(type(a))
print()

b = ["boopathy","jai","praveen","arun"]
c = np.array(b)
print(c)
print(type(c))
print()

v = ["jai","nj",2,3,3]
m =np.array(v)
print(m)
print(type(m))
print(m.dtype)
print()

#copy Function

d = np.copy(a)
e = np.copy(c)

a[3] = 23
c[1] = "Palani"
print(a,c,d,e)

[1 2 3 4 5]
<class 'numpy.ndarray'>

['boopathy' 'jai' 'praveen' 'arun']
<class 'numpy.ndarray'>

['jai' 'nj' '2' '3' '3']
<class 'numpy.ndarray'>
<U21

[ 1  2  3 23  5] ['boopathy' 'Palani' 'praveen' 'arun'] [1 2 3 4 5] ['boopathy' 'jai' 'praveen' 'arun']


In [11]:
NARR = [[23,33,44,45,66,77],[23,43,455,54,65,57],[31,233,23,232,444,65],[24,35,46,54,68,47]]
g = np.array(NARR,ndmin = 4)   # we can mention the dimensions
print(g)
print(g.ndim)

[[[[ 23  33  44  45  66  77]
   [ 23  43 455  54  65  57]
   [ 31 233  23 232 444  65]
   [ 24  35  46  54  68  47]]]]
4


In [16]:
#By Numerical Numbers

import numpy as np

#arange()

a = np.arange(20) # arange() create a array of range given
print(a)
print()

b = np.arange(450,464) # start and end is given in tuple
print(b)
print()

c = np.arange(1,20,2) #creating a array by giving step value
print(c)
print()

#Linspace()

d = np.linspace(1,10,15) #create a array that are equally spaced between the values that given start to  end
print(d)
print()

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]

[450 451 452 453 454 455 456 457 458 459 460 461 462 463]

[ 1  3  5  7  9 11 13 15 17 19]

[ 1.          1.64285714  2.28571429  2.92857143  3.57142857  4.21428571
  4.85714286  5.5         6.14285714  6.78571429  7.42857143  8.07142857
  8.71428571  9.35714286 10.        ]



The Other Methods to create array

logspace()
empty()
identify()
full()
asarray()
core.defchararray.array()
gemspace()


In [ ]:
# Arithmetic operations in numpy

import numpy as np

a = np.arange(1,20,3)
print(a)
print()
print(a+10)
print()
print(a-2)
print()
print(a*5)


[ 1  4  7 10 13 16 19]

[11 14 17 20 23 26 29]

[-1  2  5  8 11 14 17]

[ 5 20 35 50 65 80 95]


In [ ]:
#  arithmetic operation in single dimension array

a = np.arange(10,20)
b = np.arange(30,40)

print(a+b)
print()
print(a-b)
print()
print(a*b)
print()
print(np.dot(a,b))

[40 42 44 46 48 50 52 54 56 58]

[-20 -20 -20 -20 -20 -20 -20 -20 -20 -20]

[300 341 384 429 476 525 576 629 684 741]

5085


In [ ]:
#Dot Matrices
a = np.arange(9).reshape(3,3)
b = np.arange(10,19).reshape(3,3)
print(a)
print(b)
c = np.dot(a,b)
print(c)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]
[[ 45  48  51]
 [162 174 186]
 [279 300 321]]


In [ ]:
# Arithmatic operation in multidimensional array
a = np.arange(9).reshape(3,3)
b = np.arange(10,19).reshape(3,3)
print(a+b)
print(b*a)

[[10 12 14]
 [16 18 20]
 [22 24 26]]
[[  0  11  24]
 [ 39  56  75]
 [ 96 119 144]]


In [ ]:
#Perform Hill Cipher Usin Matrix Product

'''1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26
   a b c d e f g h i  j  k  l  m  n  o  p  q  r  s  t  u  v  w  x  y  z
   [e d]=[5 4]
   [u r]=[21 18]
   [e k]=[5 11]
   cipher = [[11,9],[8,17]]
   '''

# first block

a  = np.array([5,4])
cipher_key = np.array([11,9,8,17]).reshape(2,2)

e_d = np.dot(a,cipher_key)
print(e_d)
print()
e_d = np.mod(e_d,26)
print(e_d)
print()

# Second block

b  = np.array([21,18])
u_r = np.dot(a,cipher_key)
print(u_r)
print()
u_r = np.mod(u_r,26)
print(u_r)
print()

# Third block

a  = np.array([5,11])
e_k = np.dot(a,cipher_key)
print(e_k)
print()
e_k = np.mod(e_k,26)
print(e_k)
print()
print(e_k.ndim)



[ 87 113]

[9 9]

[ 87 113]

[9 9]

[143 232]

[13 24]

1
